file_format: "1"
id: 32-key-card
name: 32-key-card
type: shield
url: https://github.com/ftoralesacosta/zmk-config/tree/master/config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - 32-key-card_left
  - 32-key-card_right

