file_format: "1"
id: 32_key_card
name: 32_key_card
type: shield
url: https://github.com/ftoralesacosta/zmk-config/tree/master/config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - 32_key_card_left
  - 32_key_card_right

