file_format: "1"
id: card
name: 32-key-card
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - 32-key-card_left
  - 32-key-card_right

